# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f571b145f2f94f58618ac701195ed2e8a65d6ea8dcc9c46e3307a94c6a18ade491fc2edea59a68e42dc9be959d8b44c343a8a979ae4dd3734ca0a693d66d4b1

test:
  secret_key_base: 4ce1ba35f9e47a21bf3d18eb4225a5b94a9dfdac777fcbd4f7eb0f7672e09d7b1658abdb74bc3ca38fb1e995f7fa9f1ba6681c97c7a3b05f2562cb7beecf33b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
